kind: Deployment
apiVersion: apps/v1
metadata:
   name: devopsengineer
spec:
   replicas: 3
   selector:     
      matchLabels:
         app: devopsengineer
   template:
      metadata:
         labels:
            app: devopsengineer
      spec:
         containers:
            - name: devopsengineer
              image: devops7k/jenkins-pipeline
              imagePullPolicy: Always
              ports:
               - containerPort: 80
