kind: Service                             
apiVersion: v1
metadata:
  name: devopsengineer
  labels:
    app: devopsengineer
spec:
  ports:
    - port: 8080                               
      targetPort: 80
      nodePort: 32100
  selector:
    app: devopsengineer                    
  type: LoadBalancer                   
